CC=gcc
CFLAGS = -fPIC -Wall
LDLIBS = ../liblmc.so
CLIENTS= test

.PHONY: build
build: $(CLIENTS)

$(LDLIBS):
	@$(MAKE) -C $(SRCDIR) -f Makefile.lin $(foreach LIB,$(LDLIBS),$(notdir $(LIB)))

test: test.o $(LDLIBS)

test.o: test.c


.PHONY: clean
clean:
	rm -f test.o $(CLIENTS)
